files:
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  - source: /docs/**/*
    ignore:
      - CHANGELOG.md
      - charts/**/index.md
      - default_port_list.md
      - volume_list.md
      - description_list.md
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/about/**/%original_file_name%
  - source: /blog/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%
