/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

module.exports = {
  manualSidebar: [
    'manual/intro',
    'manual/scope',
    'manual/FAQ',
    {
      type: 'html',
      value: '<hr>', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },
    {
      type: 'category',
      label: 'Helm',
      items: [
        {
          type: 'autogenerated',
          dirName: 'manual/helm'
        },
      ]
    },
    {
      type: 'html',
      value: '<hr>', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },
    {
      type: 'category',
      label: 'KubeApps',
      items: [
        {
          type: 'autogenerated',
          dirName: 'manual/kubeapps'
        },
      ]
    },
    {
      type: 'html',
      value: '<hr>', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },
    {
      type: 'category',
      label: 'FluxCD',
      items: [
        {
          type: 'autogenerated',
          dirName: 'manual/fluxcd'
        },
      ]
    },
    {
      type: 'html',
      value: '<hr>', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },
    {
      type: 'category',
      label: 'SCALE',
      items: [
        {
          type: 'autogenerated',
          dirName: 'manual/SCALE'
        },
      ]
    },
    {
      type: 'html',
      value: '<hr>', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },
    {
      type: 'category',
      label: 'Rancher',
      items: [
        {
          type: 'autogenerated',
          dirName: 'manual/rancher'
        },
      ]
    },
    {
      type: 'html',
      value: '<hr>', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },
    {
      type: 'category',
      label: 'ArgoCD',
      items: [
        {
          type: 'autogenerated',
          dirName: 'manual/argocd'
        },
      ]
    },
    {
      type: 'html',
      value: '<hr>', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        {
          type: 'autogenerated',
          dirName: 'manual/development'
        },
      ]
    },
	{
      type: 'html',
      value: '<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9270569596814796" crossorigin="anonymous"></script><ins class="adsbygoogle"style="display:block" data-ad-client="ca-pub-9270569596814796" data-ad-slot="3096055090" data-ad-format="auto" data-full-width-responsive="true"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script>',
      defaultStyle: true, // Use the default menu item styling
    },
  ],
  chartsSidebar: [{ type: 'autogenerated', dirName: 'charts' }],
  // not used yet
  // aboutSidebar: [{ type: 'autogenerated', dirName: 'about' }],
}
