name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@3cef36a9aba515d8726b491905b3bc766832e221 # v39.0.5
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.BOT_TOKEN }}
